name: Build & Deploy

on:
  push:
    branches: -workflows_build

jobs:
  build:
    runs-on: ubuntu-lastest

  steps:
    - name: Run sh script
    - run: sh ./deploy.sh
      env:
        EMAIL: ${{ secrets.EMAIL }}
        USERNAME: ${{ secrets.USERNAME }}
