name: Build & Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v2
      - name: Run sh script
      - run: sh ./deploy.sh
        env:
          EMAIL: ${{ secrets.EMAIL }}
          USERNAME: ${{ secrets.USERNAME }}
